### ISSUE TITLE
Fix `extends` case where inherited variables are used by children or vice versa

### ISSUE THREAD

**Issue by stjohnfinn** [stjohnfinn/Sycamore#23]
Handle these use cases
```
.extended:
  variables:
    ID: $CI_PIPELINE_ID

.job:
  extends:
    - .extended
  variables:
    NAME: build-$ID
```
roughly translates to
```
export ID="$CI_PIPELINE_ID"
export NAME="build-$ID"
```

**AND**

```
.extended:
  variables:
    NAME: build-$ID

.job:
  extends:
    - .extended
  variables:
    ID: $CI_PIPELINE_ID
```
roughly translates to
```
export NAME="build-$ID"
export ID="$CI_PIPELINE_ID"
```

Both of these are valid in GitLab pipelines.  Handle both.
